<?php

$dsn = getenv('KADUPUL_TEST_MYSQL_DSN');
if (!$dsn) {
	throw new RuntimeException('Set KADUPUL_TEST_MYSQL_DSN to an isolated test database.');
}

$db = new PDO($dsn, getenv('KADUPUL_TEST_MYSQL_USER') ?: 'root', getenv('KADUPUL_TEST_MYSQL_PASSWORD') ?: '', [
	PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
	PDO::ATTR_EMULATE_PREPARES => false,
]);
$failUpdate = false;
$install_options = ['install_eula' => 'on'];

function __($message) {
	$args = func_get_args();
	array_shift($args);

	return cacti_sizeof($args) ? vsprintf($message, $args) : $message;
}

function cacti_sizeof($value) {
	return is_countable($value) ? count($value) : 0;
}

function read_config_option($name, $force = false) {
	global $install_options;

	return ($install_options[$name] ?? '');
}

function set_install_config_option($name, $value) {
	global $install_options;

	$install_options[$name] = $value;
}

function log_install_always($key, $message) {
}

function log_install_high($key, $message) {
}

function db_execute_prepared($sql, $parameters) {
	global $db, $failUpdate;
	return $failUpdate ? false : $db->prepare($sql)->execute($parameters);
}

function check_branding_migration($condition, $message) {
	if (!$condition) {
		throw new RuntimeException($message);
	}
}

require dirname(__DIR__, 2) . '/lib/installer.php';
$migration = new ReflectionMethod(Installer::class, 'migrateProductDefaults');
$migration->setAccessible(true);
$cases = [
	['Generated by Cacti®', 'Generated by Kadupul'],
	['Operations graphs © 2026', 'Operations graphs © 2026'],
	['generated by cacti®', 'generated by cacti®'],
	['Generated by Cacti® ', 'Generated by Cacti® '],
	['', ''],
	['Generated by Kadupul', 'Generated by Kadupul'],
];

foreach (['utf8mb4', 'latin1'] as $charset) {
	$db->exec('DROP TEMPORARY TABLE IF EXISTS settings');
	$db->exec("CREATE TEMPORARY TABLE settings (name VARCHAR(255) PRIMARY KEY, value TEXT) CHARACTER SET $charset");
	foreach ($cases as [$stored, $expected]) {
		$db->exec('DELETE FROM settings');
		db_execute_prepared('INSERT INTO settings VALUES (?, ?)', ['graph_watermark', $stored]);
		db_execute_prepared('INSERT INTO settings VALUES (?, ?)', ['other_setting', 'unchanged']);
		$_SESSION = ['sess_config_array' => ['graph_watermark' => $stored, 'other_setting' => 'unchanged']];
		$config = ['config_options_array' => ['graph_watermark' => $stored, 'other_setting' => 'unchanged']];
		check_branding_migration($migration->invoke(null), "$charset migration failed");
		check_branding_migration($migration->invoke(null), "$charset repeated migration failed");
		$rows = $db->query('SELECT name, value FROM settings ORDER BY name')->fetchAll(PDO::FETCH_KEY_PAIR);
		check_branding_migration($rows === ['graph_watermark' => $expected, 'other_setting' => 'unchanged'], "$charset changed a custom value or missed the default");
		check_branding_migration($_SESSION['sess_config_array'] === ['other_setting' => 'unchanged'], 'Web cache was not invalidated correctly');
		check_branding_migration($config['config_options_array'] === ['other_setting' => 'unchanged'], 'CLI cache was not invalidated correctly');
	}
}

$failUpdate = true;
check_branding_migration($migration->invoke(null) === false, 'Database failure was not propagated');

$install_options = [
	'install_eula'    => 'on',
	'install_started' => '',
];
$failing_installer = new class {
	public function setDefaults() {
	}

	public function install() {
		set_install_config_option('install_step', Installer::STEP_ERROR);
	}
};

Installer::beginInstall('-b', $failing_installer);
check_branding_migration((int) read_config_option('install_step', true) === Installer::STEP_ERROR, 'Shared installer entry point no longer preserves web error state');

$root = dirname(__DIR__, 2);
foreach (['cli/install_cacti.php', 'install/background.php'] as $entry) {
	check_branding_migration(strpos(file_get_contents("$root/$entry"), 'Installer::beginInstall(') !== false, "$entry no longer uses the shared installer");
}
$source = file_get_contents("$root/lib/installer.php");
check_branding_migration(strpos($source, '$installer->install();') !== false, 'The shared entry point no longer runs installation');
check_branding_migration(strpos($source, 'if (empty($failure) && !self::migrateProductDefaults())') !== false, 'The shared installer no longer gates completion on the migration');

print "PASS: 12 database cases across utf8mb4 and latin1; idempotence, cache invalidation, failure propagation, and CLI/web wiring.\n";
