version: 2
updates:
  - package-ecosystem: composer
    directories:
      - /
      - /tests
    target-branch: main
    labels: [dependencies, no-changelog]
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      php-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directories:
      - /
      - /tests/e2e
    target-branch: main
    labels: [dependencies, no-changelog]
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      javascript-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    labels: [dependencies, no-changelog]
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories:
      - /
      - /tests/behavior
    target-branch: main
    labels: [dependencies, no-changelog]
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
