platform:
    resource:
        path: '../src/Platform/Infrastructure/Symfony/Controller/'
        namespace: Kadupul\Platform\Infrastructure\Symfony\Controller
    type: attribute

identity_access:
    resource:
        path: '../src/IdentityAccess/Infrastructure/Symfony/Controller/'
        namespace: Kadupul\IdentityAccess\Infrastructure\Symfony\Controller
    type: attribute

inventory:
    resource:
        path: '../src/Inventory/Infrastructure/Symfony/Controller/'
        namespace: Kadupul\Inventory\Infrastructure\Symfony\Controller
    type: attribute

graphing:
    resource:
        path: '../src/Graphing/Infrastructure/Symfony/Controller/'
        namespace: Kadupul\Graphing\Infrastructure\Symfony\Controller
    type: attribute

navigation:
    resource:
        path: '../src/Navigation/Infrastructure/Symfony/Controller/'
        namespace: Kadupul\Navigation\Infrastructure\Symfony\Controller
    type: attribute
