<?php

/*
 * SPDX-FileCopyrightText: 2026 The Kadupul project and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData;
use SebastianBergmann\CodeCoverage\Report\Clover;

$root = dirname(__DIR__, 2);
require $root . '/include/vendor/autoload.php';
if ($argc !== 6) {
    throw new RuntimeException('Usage: merge_coverage.php UNIT.php FILE_SESSIONS DATABASE_SESSIONS OFFLINE_TOOLS OUTPUT.xml');
}
// This serialized artifact is generated by PHPUnit in this same job.
$coverage = require $argv[1];
if (!$coverage instanceof CodeCoverage) {
    throw new RuntimeException('Invalid Symfony unit coverage');
}
$mapped = [];
// Require the physical guarded caller, separately from any utility/helper hit.
$wrapperStatement = '$changed = (new \Kadupul\Inventory\Infrastructure\Legacy\PollerCacheBufferWrite($transactions))->write(';
$wrapperMatches = [];
$wrapperSource = file_get_contents($root . '/lib/utility.php');
if (!is_string($wrapperSource)) {
    throw new RuntimeException('Missing or unreadable physical buffered-cache caller source');
}
foreach (explode("\n", $wrapperSource) as $index => $sourceLine) {
    if (trim($sourceLine) === $wrapperStatement) {
        $wrapperMatches[] = $index + 1;
    }
}
if (count($wrapperMatches) !== 1) {
    throw new RuntimeException('Ambiguous physical buffered-cache caller statement');
}
$wrapperLine = $wrapperMatches[0];
foreach ([2 => 'files', 3 => 'database', 4 => 'none'] as $argument => $handler) {
    $manifest = json_decode(file_get_contents($argv[$argument] . '/observations.json'), true, 512, JSON_THROW_ON_ERROR);
    $suite = $handler === 'none' ? 'offline-tools' : 'symfony-http';
    if (($manifest['suite'] ?? '') !== $suite || ($manifest['session_handler'] ?? '') !== $handler) {
        throw new RuntimeException('Wrong integration suite or session handler');
    }
    $scripts = $handler === 'none' ? ['offline_coverage.py'] : ['session_bridge.py', 'data_input_scenarios.py', 'data_input_review_http.py', 'data_source_profile_scenarios.py', 'inventory_scenarios.py', 'details_scenarios.py', 'site_scenarios.py', 'site_catalog_scenarios.py', 'site_edit_scenarios.py', 'site_create_scenarios.py', 'device_create_scenarios.py', 'device_creation_review_scenarios.py', 'site_creation_probe.php', 'site_lifecycle_scenarios.py', 'site_collector_scenarios.py', 'site_lifecycle_probe.php', 'site_assignment_probe.php', 'site_disable_probe.php', 'database_failure_probe.php', 'site_authorization_probe.php', 'device_edit_scenarios.py', 'device_template_scenarios.py', 'device_collector_scenarios.py', 'device_state_scenarios.py', 'device_state_connection_probe.php', 'device_removal_scenarios.py', 'device_template_authorization_probe.php', 'script_server_scenarios.py', 'cli_parity_scenarios.py', 'cli_schema_scenarios.py', 'coverage_support.py', 'link_scenarios.py', 'about_scenarios.py', 'about_authentication_scenarios.py', 'palette_color_review_http.py', 'palette_color_scenarios.py', 'palette_sql_failure_probe.php', 'vdef_scenarios.py', 'vdef_transaction_probe.php', 'vdef_browser_probe.cjs', 'device_bulk_assignment_scenarios.py', 'device_bulk_snmp_scenarios.py'];
    $sourcePaths = array_map(static fn(string $script): string => 'tests/Symfony/' . $script, $scripts);
    if ($handler !== 'none') {
        // Bind the bodyless contract without inventing coverage for its declaration.
        $sourcePaths[] = 'src/Platform/Contract/ReferenceWriteTransactionRunner.php';
        $sourcePaths[] = 'src/Platform/Infrastructure/Legacy/NativeReferenceWriteTransactionRunner.php';
        $sourcePaths[] = 'tests/Symfony/cdef_legacy_page_scenarios.py';
        $sourcePaths[] = 'tests/e2e/browser-coverage.js';
        $sourcePaths[] = 'public/js/vdef-item.js';
        $sourcePaths[] = 'tests/Fixtures/plugins/compatibility_test/setup.php';
        // cli_parity_scenarios.py and cli_schema_scenarios.py compare the shims
        // against these frozen originals.
        $sourcePaths[] = 'tests/Fixtures/legacy-cli/analyze_database.php';
        $sourcePaths[] = 'tests/Fixtures/legacy-cli/convert_tables.php';
        $sourcePaths[] = 'tests/Fixtures/legacy-cli/fix_mediumint.php';
    }
    foreach ($sourcePaths as $path) {
        if (($manifest['source_sha256'][$path] ?? '') !== hash_file('sha256', $root . '/' . $path)) {
            throw new RuntimeException('Integration test source differs from checkout');
        }
    }
    $checks = $handler === 'none' ? ['disconnected archive verified', 'dependency repair verified', 'invalid manifest and symlink rejected'] : [
        'selected PDO runner preserves primary and collector identities and caller-owned work',
        'system page size fixture restores original absence and value',
        'profile deletion confirmation page renders',
        'unused profile is normally removable',
        'collector retry builds real poller item from the saved command',
        'offline collector yields explicit partial handoff without undoing local definition',
        'whitelist update publishes the exact saved command and verifies it',
        'worker independently rechecks feature grants before executing the handoff',
        'French session authenticates through legacy login',
        'French editor translates presentation without changing raw command definition',
        'English field deletion confirmation uses a readable action label',
        'French field deletion confirmation honors the authenticated preference',
        'About unprotected Basic headers cannot establish a web-server principal',
        'About Basic identity is verified by Apache before PHP',
        'About first Basic request restores native identity through the legacy forwarder',
        'About Basic restoration resumes About without granting console realm 8',
        'About restored Basic session refuses a revoked account',
        'About Basic transition publishes a native credential cookie',
        'About remembered transition publishes protected session and replacement cookies',
        'About first remembered request restores the native cookie identity',
        'About remembered restoration resumes About without granting console realm 8',
        'About remembered restoration consumes and rotates the exact native token',
        'About consumed remembered token cannot be replayed',
        'About replacement remembered token establishes a fresh native session',
        'About restored remembered session refuses a disabled account',
        'About requires login without console realm 8', 'About version and beta are escaped without legacy bootstrap',
        'quoted newline CSV upload succeeds', 'CSV exact name data handoff',
        'links French fixture restores exact original global and actor language settings',
        'palette large pages keep all rows readable but enable at most 100 deletable choices',
        'palette 100-color confirmation preserves every selected identity and revision',
        'palette forged 101-color selection is refused before mutation',
        'silent palette SQL failures preserve rows and refuse false saves imports and dependency deletes',
        'palette writes refuse actual nontransactional tables, invalid collectors and caller transactions without losing prior work',
        'palette preferences refuse actual nontransactional tables, invalid collectors and caller transactions while primary saves commit',
        'palette writes and preferences reject all InnoDB temporary shadows without changing persistent observer rows',
        'two palette actors authorize concurrently while policy, account and realm revokers wait and later denials take effect',
        'duplicate hex creation is a known validation failure after rollback',
        'duplicate hex edit is a known validation failure after rollback',
        'duplicate hex edit preserves the original name and hex',
        'unnamed palette color has a visible edit link and accessible hex label',
        'palette Unicode invisible names use accessible hex labels while visible names and CSV bytes remain exact',
        'palette exports neutralize formulas and preserve exact versioned roundtrip names',
        'unsupported or malformed palette literal marker rejects the whole import',
        'ordinary legacy CSV import preserves its leading apostrophe literally',
        'console-only palette account cannot parse or mutate any route',

        'transaction rollback restores prior import updates', 'missing palette realm rejected',
        'VDEF caller transaction and remote collector guards verified on MariaDB',
        'VDEF writes reject every InnoDB temporary participant and preserve persistent observer rows',
        'VDEF malformed list arrays return controlled 400 before catalog reads: filter',
        'VDEF malformed list arrays return controlled 400 before catalog reads: sort',
        'VDEF malformed list arrays return controlled 400 before catalog reads: direction',
        'VDEF malformed list arrays return controlled 400 before catalog reads: has_graphs',
        'VDEF own legacy reference deletes through CSRF form: 0',
        'VDEF own legacy reference deletes through CSRF form: 1',
        'VDEF own legacy reference deletes through CSRF form: 2',
        'VDEF own legacy reference deletes through CSRF form: 3',
        'VDEF own legacy reference deletes through CSRF form: 4',
        'VDEF own legacy reference deletes through CSRF form: 5',
        'VDEF own legacy reference deletes through CSRF form: 6',
        'VDEF own legacy reference deletes through CSRF form: 7',
        'VDEF whole selected reference set deletes through CSRF form',
        'VDEF array type query returns controlled 400 without mutation',
        'VDEF unknown item deletion uses French catalog label',
        'VDEF nested reference refuses function overwrite', 'VDEF browser type change and save pass under CSP',
        'VDEF oversized legacy parent ID falls back',
        'VDEF nontransactional table refused: vdef', 'VDEF nontransactional table refused: graph_templates_item',
        'VDEF duplicate preserves all item rows', 'VDEF item deletion persists',
        'VDEF failure rolls back parent deletion', 'VDEF console-only actor refused before malformed query',
        'links deletion cleans direct and group realms', 'links stale reorder rejected', 'links grant deletion failure rolls back link deletion',
        'query parameters cannot select an authenticated session', 'deleted account cannot use persisted session',
        'Symfony command disables device polling', 'CSV quotes multiline Unicode text and neutralizes formulas',
        'site counts exclude hidden and deleted devices', 'site persistence rechecks actor and revision and rolls back rejected saves',
        'site write serializes account, policy, direct and group grant revocations',
        'site rollback cannot restore a revoked session after account re-enabling',
        'Symfony site translations honor the legacy session and ignore locale query overrides',
        'disabled translation overrides a French shared session',
        'French device editor translates labels without changing polling values',
        'device CSV bytes are independent of locale',
        'device polling settings save through Symfony',
        'device template assignment saves through Symfony',
        'collector reassignment replicates primary device to remote',
        'collector replication failure cannot report success',
        'bulk state confirmation disables selected devices',
        'bulk state confirmation enables selected devices',
        'bulk state SQL failure rolls back the whole primary batch',
        'bulk state remote failure cannot report success',
        'bulk state observer records original production source identity',
        'bulk state observer uses a separate fixture source outside production coverage',
        'bulk state observer restores exact production bytes and removes owned fixtures',
        'template synchronization saves through Symfony',
        'deferred discovery failure does not publish a success audit record',
        'failed synchronization does not publish a success audit record',
        'successful synchronization publishes exactly one success audit record',
        'template synchronization refuses unauthenticated POST requests',
        'collector identity mismatch invokes no action 7 callback',
        'collector identity mismatch rolls back the primary batch',
        'deferred discovery failure reports uncertain completion',
        'deferred discovery failure retains committed associations without a success callback',
        'deferred synchronization discovery fixture registered',
        'denied synchronization performs no writes or callbacks',
        'each synchronized device receives only its own template associations',
        'failed synchronization does not invoke the bulk action callback',
        'missing template invokes no callbacks and preserves the marker',
        'missing template preserves all primary associations',
        'multiple templates do not leak associations across devices',
        'multiple templates preserve per-device and complete-selection callback contracts',
        'slow synchronization discovery does not block a concurrent poller write',
        'template synchronization GET does not add associations',
        'template synchronization GET does not add data-query associations',
        'template synchronization adds required data-query associations',
        'template synchronization adds required graph associations',
        'template synchronization association failure cannot report success',
        'template synchronization conceals inaccessible devices on GET and POST',
        'template synchronization denied-realm fixture starts authorized',
        'template synchronization discovery runs without an active primary transaction',
        'template synchronization hook registered',
        'template synchronization preserves the configured data-query reindex method',
        'template synchronization refuses an actor without the device-management realm',
        'template synchronization refuses unauthenticated requests',
        'template synchronization rejects a missing assigned template',
        'template synchronization rejects altered collector template identity',
        'template synchronization rejects offline collectors before writes',
        'template synchronization rejects stale device revisions',
        'template synchronization rejects unexpected fields',
        'template synchronization removes unused graph associations',
        'template synchronization repairs associations despite existing query cache',
        'template synchronization requires CSRF token',
        'template synchronization requires same-origin CSRF',
        'template synchronization resolves the effective default reindex method',
        'template synchronization retains associations used by existing graphs',
        'template synchronization retries safely after deferred discovery failure',
        'template synchronization skips unassigned devices',
        'template synchronization supports a selection spanning different templates',
        'template synchronization supports repeated synchronization',
        'template synchronization worker independently refuses a revoked realm',
        'template synchronization accepts an all-unassigned selection as a no-op',
        'all-unassigned template synchronization invokes no mutation callbacks',
        'all-unassigned template synchronization preserves the device-change marker',
        'template synchronization invokes the template-change hook once per assigned device',
        'template synchronization retains existing graphs',
        'template synchronization failure rolls back primary associations',
        'remote template synchronization preserves assigned template identity',
        'template synchronization invokes action 7 once with complete selection',
        'bulk options invokes action 4 once for the complete selection',
        'rejected bulk options do not invoke action 4',
        'bulk site assigns through Symfony',
        'bulk template assigns through Symfony',
        'bulk site failure rolls back whole primary selection',
        'bulk template failure rolls back whole primary selection',
        'bulk collector moves full selection to remote',
        'bulk collector returns full selection to primary',
        'bulk collector purges old remote copies',
        'collector cleanup failure retains committed primary ownership and polling rows',
        'collector cleanup failure leaves a recoverable old host copy',
        'collector cleanup failure emits no success audit',
        'collector reassignment recovers old host and polling residue through confirmed moves',
        'bulk SNMP never displays stored credentials',
        'bulk SNMP keeps each device credentials through Symfony',
        'bulk SNMP validates all stored credentials before writes',
        'bulk SNMP failure rolls back entire primary selection',
        'bulk SNMP replaces credentials through Symfony',
        'bulk SNMP verifies remote credentials',
        'bulk SNMP secrets stay out of database diagnostics',
        'bulk SNMP fixture has nonempty primary polling rows',
        'bulk SNMP fixture has nonempty remote polling rows',
        'bulk SNMP rejects nontransactional primary cache participants before writes',
        'bulk SNMP rejects nontransactional collector cache participants before writes',
        'bulk SNMP real data-source cache fixture initialized',
        'bulk SNMP action hook registered',
        'untouched bulk SNMP form leaves settings credentials and caches unchanged',
        'bulk SNMP requires same-origin CSRF',
        'bulk SNMP requires CSRF token',
        'bulk SNMP rejects unrelated nested fields',
        'bulk SNMP rejects concurrent protocol changes',
        'invalid stored credentials leave entire bulk selection unchanged',
        'invalid stored credentials leave every collector and polling cache unchanged',
        'bulk SNMP invokes action 4 once for the complete selection',
        'bulk SNMP failure hides submitted secrets',
        'bulk SNMP later primary failure preserves collector credentials and caches',
        'rejected bulk SNMP does not invoke action 4',
        'bulk SNMP later cache failure rolls back primary and collector credentials',
        'bulk SNMP cache rejection invokes no action callback',
        'bulk SNMP redirect displays its completion notice',
        'bulk SNMP persists replacement credentials',
        'bulk SNMP replacement reaches primary and collector polling rows',
        'bulk SNMP applies validated version 3 credentials',
        'bulk SNMP version 3 secrets reach primary and remote polling caches',
        'untouched version 3 bulk form retains every secret and protocol',
        'bulk SNMP rejects a later stored seven-byte passphrase without writes',
        'bulk SNMP stored passphrase denial uses the actual actor French preference',
        'bulk SNMP accepts stored eight-byte passphrases',
        'bulk SNMP keeps distinct stored authentication secrets in polling rows',
        'bulk SNMP rejects stored NUL credentials before every write',
        'bulk SNMP permits leaving version 3',
        'bulk version change preserves every unchecked credential and protocol',
        'bulk SNMP disables protocol through Symfony',
        'bulk SNMP success emits the actor and complete-selection audit line',
        'bulk SNMP preserves individual stored communities',
        'bulk SNMP rebuilds polling rows with each devices credentials',
        'bulk SNMP rejects oversized and NUL replacement credentials without writes',
        'bulk SNMP disabling clears primary and remote reindex state',
        'device list exposes all bulk assignment routes',
        'default mutation selection retains existing missing-site and disabled-poller behavior',
        'bulk site invokes action 4 once for the complete selection',
        'bulk template invokes action 4 once for the complete selection',
        'rejected bulk site does not invoke action 4',
        'rejected bulk template does not invoke action 4',
        'bulk site displays its assignment completion notice',
        'bulk template displays its assignment completion notice',
        'bulk existing template repairs missing association',
        'bulk existing template restores primary and collector association',
        'bulk template assignment retains existing graphs and data',
        'bulk template unassignment invokes the zero-template hook for each device',
        'bulk template preserves site membership cache marker',
        'bulk collector worker rejects disabled destination after GET',
        'disabled bulk collector destination writes no ownership or copy',
        'bulk collector return failure reports uncertain outcome',
        'bulk collector return failure rolls back primary ownership and statistics',
        'bulk collector rollback retains every previous polling copy',
        'bulk collector transfers a full remote selection to another remote',
        'bulk remote transfer confirms primary and destination ownership',
        'bulk remote transfer preserves nonempty polling ownership',
        'bulk remote transfer removes old copies after commit',
        'bulk collector can return to its previous remote',
        'bulk remote return cleans the second collector',
        'bulk collector mid-batch failure reports uncertain outcome',
        'bulk collector mid-batch failure rolls back primary host and cache ownership',
        'bulk collector mid-batch failure rolls back poller statistics',
        'rejected bulk collector does not invoke action 4',
        'bulk collector failure retains documented first-device remote residue',
        'bulk site worker rejects deleted destination after GET without writes',
        'malformed bulk assignment command cannot write',
        'bulk assignment worker rejects extra command keys before writes',
        'bulk site preserves preflight remote disabled state',
        'bulk template preserves preflight remote disabled state',
        'bulk collector cleanup rejects changed ownership before purging',
        'bulk collector cleanup failure cannot report success',
        'bulk collector cleanup failure retains committed destination ownership',
        'bulk collector cleanup failure leaves recoverable old copies',
        'bulk collector recovers old residue by returning to remote',
        'collector acknowledgement failure cannot report success after remote cleanup',
        'collector failed acknowledgement retains receipt despite verified remote absence',
        'bulk collector later acknowledgement failure cannot report success',
        'bulk collector failed acknowledgement rolls back all receipts after remote absence',
        'collector cleanup failure persists old-owner retry receipt',
        'collector same-target retry reports repeated cleanup failure',
        'collector failed retry retains old copy and receipt',
        'collector disabled pending owner refuses cleanup retry',
        'collector unavailable cleanup retains retry receipt',
        'collector successful same-target retry removes old dependent copies',
        'collector successful cleanup acknowledges retry receipt',
        'collector verified cleanup publishes no redundant purge command',
        'bulk collector cleanup failure persists complete retry inventory',
        'bulk collector same-target retry reports repeated cleanup failure',
        'bulk collector failed retry retains complete cleanup inventory',
        'bulk collector same-target retry completes pending cleanup',
        'bulk collector successful retry removes old polling copies',
        'bulk collector successful cleanup acknowledges complete retry inventory',
        'bulk collector verified cleanup publishes no redundant purge commands',
        'bulk options save through Symfony',
        'bulk options action hook registered',
        'bulk options GET does not modify selected devices',
        'bulk options requires an explicit field selection',
        'bulk options requires same-origin CSRF',
        'bulk options requires CSRF token',
        'bulk options rejects assignment mass updates',
        'bulk options validates selected polling values',
        'bulk options rejects concurrent option edits',
        'bulk option edits invalidate removal confirmations',
        'stale options removal confirmation preserves selected devices',
        'bulk options worker rejects enabled payload',
        'bulk options worker rejects non-array changes',
        'malformed options worker payloads preserve data and callbacks',
        'bulk options rejects selected invalid ping choice',
        'bulk options rejects selected invalid availability choice',
        'bulk options rejects offline collectors before writes',
        'bulk options write failure cannot report success',
        'bulk options stored-value mismatch cannot report success',
        'bulk options stored-value mismatch rolls back entire primary batch',
        'bulk options stored-value mismatch does not invoke action 4',
        'bulk options completion banner renders exactly once',
        'bulk options unchanged values succeed on repeated submission',
        'bulk options unchanged submissions preserve primary values',
        'bulk options unchanged submissions preserve collector values',
        'bulk options saves selected availability and ping choices',
        'bulk options persists choices on primary',
        'bulk options persists choices on collector',
        'bulk options allows clearing location and ignores unchecked invalid values',
        'bulk options ignores unchecked invalid choices',

        'bulk options failure rolls back entire primary batch',
        'bulk options verifies remote values',
        'bulk options changes selected fields and preserves unchecked values',
        'statistics confirmation resets selected devices',
        'statistics SQL rejection rolls back entire primary selection',
        'remote statistics match the legacy reset',
        'statistics reset invokes action 5 once with the complete selection',
        'rejected statistics resets do not invoke action 5 callbacks',
        'repeated statistics reset invokes action 5 once',
        'device removal retains graphs and disabled data sources',
        'device removal purges graphs and all owned data sources',
        'device removal failure rolls back whole primary batch',
        'device removal rejects shared data-source purge',
        'rejected removal emits no bulk action callback',
        'remote removal failure cannot report success',
        'remote removal rejects outside graph references before cleanup',
        'remote removal failure rolls back dependent cleanup',
        'collector association failure cannot report successful template assignment',
        'SNMP credentials replace through Symfony without disclosure',
        'stored credential rotation survives unrelated edits',
        'all polling fields persist through the legacy adapter',
        'device site assignment saves through Symfony',
        'site reassignment invalidates device and site caches',
        'site creation persists name',
        'site creation updates both legacy cache markers',
        'rejected creations leave all sites unchanged',
        'full site address timezone map and alternate name persist',
        'bulk site deletion succeeds atomically',
        'site locks precede device locks and rejected assignments preserve polling state',
        'transactional SQL failures cannot retry without locks or report a saved ID',
        'bulk duplication succeeds through Symfony',
        'site lifecycle adapter rejects revoked stale and partial writes',
        'legacy site POST is never replayed',
        'online collector site edit writes only to the primary',
        'unreachable primary cannot fall back to local site writes',
        'worker independently rechecks revoked actor permissions',
        'legacy template graph associations are preserved',
        'device creation updates both cache markers',
        'explicit credentials are not replaced by installation defaults',
        'device creation serializes direct authorization revocations',
        'device creation serializes group authorization revocations',
        'remote collector preserves four-byte Unicode notes',
        'SHA384 is preserved without mapping to an invalid protocol',
        'script server answers valid calls and refuses invalid ones with U',
        'script server refuses includes outside the scripts directory',
        'script server never dispatches PHP internals',
        'script server answers 404 over HTTP',
        'analyze: shim analyzes every table through the kernel container',
        'analyze invalid flag: shim stdout matches the original',
        'shim analyzes every table as the operator named by --as',
        'unknown operator is refused without naming the account',
        'absent admin_user: shim matches the original',
        'convert innodb: shim converts the table through the kernel container',
        'convert installer call: shim schema matches the original',
        'convert missing table: shim logs the same CONVERT FATAL line, date included',
        'convert missing table with d.m.Y dates: shim logs the same CONVERT FATAL line, date included',
        'analyze: shim logs the same completion line, date included',
        'convert missing table: shim sends no statement for a table the server does not list',
        'convert tables refuses a run with no operator',
        'convert tables refuses an operator without the Installation/Upgrades realm',
        'convert tables refuses an empty --as rather than falling back to admin_user',
        'convert tables falls back to Settings/Utilities while nobody holds Installation/Upgrades',
        'convert tables fallback still needs a direct Settings/Utilities grant',
        'convert tables sends no DDL for a table name the server does not list',
        'installer converts a queued MyISAM table to InnoDB and utf8mb4 in-process',
        'installer logs the queued conversion through log_install_always',
        'widen narrowed columns: shim widens the columns the original statement missed',
        'widen narrowed columns: only the original logs the statement that failed',
        'widen narrowed columns debug: shim stdout matches the original',
        'widen fresh schema: shim logs the same cacti.log lines, date included',
        'widen never narrows a bigint column',
        'widen keeps a nullable column nullable',
        'widen alters a hostile table name as one quoted identifier',
        'widen refuses an unknown operator before any statement',
        'widen refuses an empty --as rather than falling back to admin_user',
        'widen refuses a run with no operator',
        'widen refuses an operator without the Installation/Upgrades realm',
        'widen fallback still needs a direct Settings/Utilities grant',
        'widen falls back to Settings/Utilities while nobody holds Installation/Upgrades',
        'widen --dry-run through bin/console plans each table and changes nothing',
        'widen scenarios leave the schema as they found it'];
    // The original installed scenario, its completed behavior checks and each page's
    // actual source hash are required before these legacy caller observations enter Clover.
    $legacyCallerPaths = $handler === 'none' ? [] : ['graphs.php', 'cdef.php',
        'aggregate_templates.php', 'color_templates.php', 'aggregate_graphs.php', 'lib/utility.php'];
    if ($handler !== 'none') {
        $checks = array_merge($checks, [
            'installed CDEF duplication preserves persisted parent and children',
            'installed CDEF referenced deletion refuses and preserves actual records',
            'installed CDEF unused deletion removes actual parent and children',
            'installed CDEF child copy refusal reports exact partial parent and preserves original definition',
            'installed legacy write requires actual CSRF before mutation: /cdef.php',
            'installed legacy write refuses the revoked actor realm before mutation: /cdef.php',
            'installed legacy write requires actual CSRF before mutation: /graphs.php',
            'installed legacy write refuses the revoked actor realm before mutation: /graphs.php',
            'installed aggregate template save persists rendered graph item cache',
            'installed aggregate malformed item request refuses before metadata writes',
            'installed aggregate cache refusal preserves cache and reports independently saved metadata',
            'installed aggregate propagation refusal reports saved metadata and preserves graph participants',
            'installed graphs confirmation leaves all nine participants unchanged: 9',
            'installed graphs confirmation leaves all nine participants unchanged: 10',
            'installed graphs aggregation persists exact selected member and generated items: 9',
            'installed graphs aggregation persists exact selected member and generated items: 10',
            'installed graph malformed color refuses with all nine participants unchanged',
            'installed graph late generation refusal rolls back all nine participants',
            'installed graph editor renders persisted graph device and data source identities without mutation',
            'installed graph autocomplete returns exact persisted owned data source identity without mutation',
            'installed deleted graph editor reports missing resource without mutation',
            'installed color synchronization reports genuine empty usage',
            'installed color synchronization regenerates actual template and standalone cohorts',
            'installed color second cohort refusal preserves failed graph and reports earlier committed cohort',
            'installed color discovery failure reports refusal instead of empty usage',
            'installed aggregate graph editor saves actual rendered settings and member identity',
            'installed aggregate graph malformed request refuses before all nine participant writes',
            'installed aggregate graph cache refusal preserves cache and reports saved title',
            'installed aggregate graph regeneration refusal preserves generated items and reports saved settings',
            'installed legacy CDEF aggregate and color page scenarios completed cleanup',
        ]);
    }
    foreach ($checks as $check) {
        if (!in_array($check, $manifest['checks'] ?? [], true)) {
            throw new RuntimeException('Incomplete Symfony integration checks');
        }
    }
    $reports = glob($argv[$argument] . '/raw/coverage-*.json');
    if (!$reports) {
        throw new RuntimeException('Missing integration coverage reports');
    }
    $observed = [];
    $wrapperObserved = false;
    foreach ($reports as $report) {
        $data = json_decode(file_get_contents($report), true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($data['files'] ?? null) || !is_string($data['php'] ?? null)) {
            throw new RuntimeException('Malformed integration coverage report');
        }
        foreach ($data['files'] as $path => $file) {
            if (!str_starts_with($path, '/var/www/html/')) {
                throw new RuntimeException('Unexpected integration source path');
            }
            $relative = substr($path, strlen('/var/www/html/'));
            // Legacy application coverage has its own report. Never import
            // generated configuration/cache, dependencies or installed plugins.
            // The script server and cli/ shims are listed
            // because only a subprocess or an HTTP request can reach their entry guards.
            if (!str_starts_with($relative, 'src/') && !in_array($relative, $legacyCallerPaths, true) && !in_array($relative, ['bin/legacy-data-input.php', 'bin/legacy-data-input-handoff.php', 'lib/data_input_worker.php', 'lib/api_device.php', 'data_input.php', 'script_server.php', 'cli/analyze_database.php', 'cli/convert_tables.php', 'cli/fix_mediumint.php', 'bin/legacy-device-edit.php', 'bin/legacy-device-create.php', 'bin/legacy-device-template.php', 'bin/legacy-device-collector.php', 'bin/legacy-assignment-bootstrap.php', 'bin/legacy-device-state.php', 'bin/legacy-device-remove.php', 'app.php', 'sites.php', 'lib/database.php', 'public/index.php', 'config/bootstrap.php', 'tools/verify-offline.php', 'tools/dependencies/install-legacy.php', 'links.php', 'about.php', 'color.php', 'vdef.php'], true)) {
                continue;
            }
            $local = $root . '/' . $relative;
            if (realpath($local) !== $local || !is_file($local)) {
                throw new RuntimeException('Invalid integration source path');
            }
            if (!is_array($file) || ($file['sha256'] ?? null) !== hash_file('sha256', $local)) {
                throw new RuntimeException('Covered source differs from checkout: ' . $relative . ' (' . $handler . ', ' . basename($report) . ')');
            }
            if (!is_array($file['lines'] ?? null)) {
                throw new RuntimeException('Invalid line coverage inventory');
            }
            $lineCount = substr_count(file_get_contents($local), "\n") + 1;
            foreach ($file['lines'] as $line => $hit) {
                if (!is_int($line) || $line < 1 || $line > $lineCount || !in_array($hit, [-1, 1], true)) {
                    throw new RuntimeException('Invalid PCOV line observation');
                }
                $mapped[$local][$line] = max($mapped[$local][$line] ?? -1, $hit);
                $observed[$relative] = ($observed[$relative] ?? false) || $hit === 1;
                if ($relative === 'lib/utility.php' && $line === $wrapperLine && $hit === 1) {
                    $wrapperObserved = true;
                }
            }
        }
    }
    $requiredPaths = $handler === 'none' ? ['tools/verify-offline.php', 'tools/dependencies/install-legacy.php'] : [
        'links.php',
        'src/Navigation/Infrastructure/Legacy/LegacyLinkStore.php',
        'src/Navigation/Infrastructure/Symfony/Controller/LinkEditController.php',
        'src/DataInput/Infrastructure/Legacy/DataInputHandoff.php',
        'bin/legacy-data-input.php', 'bin/legacy-data-input-handoff.php', 'lib/data_input_worker.php', 'data_input.php', 'src/DataInput/Infrastructure/Symfony/Controller/DataInputController.php', 'bin/legacy-device-edit.php', 'src/IdentityAccess/Infrastructure/Legacy/SharedSession.php',
        'src/IdentityAccess/Infrastructure/Legacy/LegacyAboutAccess.php',
        'src/IdentityAccess/Infrastructure/Legacy/LegacyBrowserAuthentication.php',
        'src/IdentityAccess/Infrastructure/Legacy/BrowserAuthenticationSql.php',
        'src/IdentityAccess/Infrastructure/Legacy/NativeAuthenticationSession.php',
        ($handler === 'database' ? 'src/IdentityAccess/Infrastructure/Legacy/AuthenticationDatabaseSessionHandler.php' : 'src/IdentityAccess/Infrastructure/Legacy/AuthenticationFileSessionHandler.php'),
        'about.php', 'src/Platform/Infrastructure/Symfony/Controller/AboutController.php',
        'src/Platform/Infrastructure/Symfony/Controller/LegacyAboutController.php',
        'src/Platform/Infrastructure/Legacy/InstallationProductVersion.php',
        'color.php',
        'src/Graphing/Domain/PaletteCsv.php',
        'src/Graphing/Infrastructure/Legacy/LegacyPaletteColorStore.php',
        'src/Graphing/Infrastructure/Legacy/PaletteSql.php',
        'src/Graphing/Infrastructure/Legacy/LegacyPaletteColorAccess.php',
        'src/Graphing/Infrastructure/Legacy/LegacyPaletteColorPreferences.php',
        'src/Graphing/Infrastructure/Symfony/Controller/PaletteColorCsvController.php',
        'src/Graphing/Infrastructure/Symfony/Controller/PaletteColorEditController.php',
        'bin/legacy-device-edit.php',
        'links.php',
        'src/Navigation/Infrastructure/Legacy/LegacyLinkStore.php',
        'src/Navigation/Infrastructure/Symfony/Controller/LinkEditController.php',
        'src/IdentityAccess/Infrastructure/Legacy/SharedSession.php',
        'vdef.php',
        'src/GraphDefinition/Infrastructure/Legacy/LegacyVdefEditor.php',
        'src/GraphDefinition/Infrastructure/Symfony/Controller/VdefItemController.php',
        'src/GraphDefinition/Infrastructure/Symfony/Controller/VdefActionController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceEditController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteListController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteEditController.php', 'src/Inventory/Infrastructure/Legacy/LegacySiteEditor.php',
        'src/IdentityAccess/Infrastructure/Legacy/LegacyLocalePreference.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteCreateController.php',
        'src/Inventory/Domain/DevicePolling.php',
        'src/Inventory/Domain/DeviceTemplateAssignment.php',
        'src/Inventory/Domain/DeviceCollectorAssignment.php',
        'src/Inventory/Infrastructure/Symfony/DeviceFormFailure.php',
        'src/Inventory/Infrastructure/Symfony/DeviceFormPage.php',
        'src/Inventory/Infrastructure/Symfony/DeviceAssignmentForm.php',
        'src/Inventory/Infrastructure/Legacy/DeviceAssignmentLock.php',
        'src/Inventory/Infrastructure/Legacy/DeviceAssignmentProcess.php',
        'src/Inventory/Application/Command/AssignDeviceTemplate.php',
        'src/Inventory/Application/Command/AssignDeviceCollector.php',
        'src/Inventory/Application/Query/PrepareDeviceTemplateAssignment.php',
        'src/Inventory/Application/Query/PrepareDeviceCollectorAssignment.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceTemplateAssignments.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceCollectorAssignments.php',
        'src/Inventory/Infrastructure/Legacy/DeviceWriteAuthorization.php',
        'src/Inventory/Infrastructure/Legacy/DeviceMutationSelection.php',
        'src/Inventory/Infrastructure/Legacy/DeviceCollectorReplication.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceTemplateType.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceCollectorType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceTemplateController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceCollectorController.php',
        'bin/legacy-device-template.php',
        'bin/legacy-device-collector.php', 'bin/legacy-assignment-bootstrap.php',
        'bin/legacy-device-state.php',
        'lib/api_device.php',
        'bin/legacy-device-remove.php',
        'src/Inventory/Domain/DeviceRemoval.php',
        'src/Inventory/Application/Command/RemoveDevices.php',
        'src/Inventory/Application/Query/PrepareDeviceRemoval.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceRemovals.php',
        'src/Inventory/Infrastructure/Legacy/DeviceRemovalSnapshot.php',
        'src/Inventory/Infrastructure/Legacy/DeviceRemovalDependencies.php',
        'src/Inventory/Infrastructure/Symfony/DeviceSelectionForm.php',
        'src/Inventory/Infrastructure/Legacy/DeviceRemovalDependencyReceipt.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceRemovalType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceRemovalController.php',
        'src/Inventory/Domain/DeviceState.php',
        'src/Inventory/Domain/DeviceSelection.php',
        'src/Inventory/Application/Command/SetDevicesEnabled.php',
        'src/Inventory/Application/Query/PrepareDeviceStateChange.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceStates.php',
        'src/Inventory/Domain/DeviceBulkAssignment.php',
        'src/Inventory/Application/Command/AssignDevices.php',
        'src/Inventory/Application/Query/ListDeviceAssignmentTargets.php',
        'src/Inventory/Infrastructure/Legacy/DeviceBulkAssignmentWriter.php',
        'src/Inventory/Infrastructure/Legacy/DeviceCollectorTransfer.php',
        'src/Inventory/Infrastructure/Legacy/DeviceCollectorCleanup.php',
        'src/Inventory/Infrastructure/Legacy/PollerCacheBufferWrite.php',
        'src/Platform/Infrastructure/Legacy/NativeReferenceWriteTransactionRunner.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceBulkAssignmentType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceBulkAssignmentController.php',
        'src/Inventory/Application/Command/ChangeDevicesSnmp.php',
        'src/Inventory/Infrastructure/Legacy/DeviceSnmpWriter.php',
        'src/Inventory/Domain/DeviceOptionsChange.php',
        'src/Inventory/Application/Command/ChangeDeviceOptions.php',
        'src/Inventory/Infrastructure/Legacy/DeviceOptionsWriter.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceOptionsType.php',
        'src/Inventory/Application/Command/ClearDeviceStatistics.php',
        'src/Inventory/Application/Command/SynchronizeDeviceTemplates.php',
        'src/Inventory/Infrastructure/Legacy/DeviceStatisticsReset.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceStateType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceStateController.php',
        'src/Inventory/Domain/DeviceSnmpConfiguration.php',
        'src/Inventory/Domain/DeviceSnmpChange.php',
        'src/Inventory/Domain/DeviceBulkSnmpChange.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceSnmpType.php',
        'src/Inventory/Infrastructure/Symfony/Form/DevicePollingType.php',
        'src/Inventory/Application/Query/ListAssignableSites.php',
        'src/Platform/Infrastructure/Doctrine/InstallationConnectionMiddleware.php',
        'src/Platform/Infrastructure/Doctrine/InstallationConnectionDriver.php',
        'src/Inventory/Infrastructure/Persistence/DoctrineSiteAssignmentCatalog.php',
        'src/Inventory/Application/Command/CreateSite.php',
        'src/Inventory/Domain/NewSite.php',
        'src/Inventory/Infrastructure/Legacy/LegacySiteCreator.php',
        'src/Platform/Infrastructure/Legacy/CollectorSiteDatabase.php',
        'sites.php',
        'lib/database.php',
        'src/Inventory/Infrastructure/Symfony/Controller/LegacySitesController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteActionController.php',
        'src/Inventory/Infrastructure/Legacy/LegacySiteLifecycle.php',
        'src/Inventory/Application/Command/DeleteSites.php',
        'src/Inventory/Application/Command/DuplicateSites.php',
        'src/Inventory/Application/Query/PrepareSiteAction.php',
        'src/Inventory/Domain/SiteSelection.php',
        'bin/legacy-device-create.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceCreateController.php',
        'src/Inventory/Application/Command/CreateDevice.php',
        'src/Inventory/Application/Query/PrepareDeviceCreation.php',
        'src/Inventory/Domain/NewDevice.php',
        'src/Inventory/Infrastructure/Persistence/DoctrineDeviceCreationCatalog.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceCreator.php',
        'src/Platform/Infrastructure/Symfony/InventoryLocaleSubscriber.php',
        'script_server.php',
        'cli/analyze_database.php',
        'src/Platform/Infrastructure/Symfony/Console/LegacyCli.php',
        'src/Platform/Infrastructure/Symfony/Console/LegacyArguments.php',
        'src/Platform/Infrastructure/Symfony/Console/AnalyzeDatabaseLegacyArguments.php',
        'src/Platform/Infrastructure/Symfony/Console/CliPresentation.php',
        'src/Platform/Infrastructure/Symfony/Console/AnalyzeDatabaseCommand.php',
        'src/Platform/Infrastructure/Symfony/Console/ResultRenderer.php',
        'src/Platform/Application/Command/AnalyzeDatabase.php',
        'src/IdentityAccess/Infrastructure/Cli/CliConsoleAccess.php',
        'src/Platform/Infrastructure/Persistence/DbalDatabaseMaintenance.php',
        'src/Platform/Infrastructure/Legacy/InstallationVersion.php',
        'src/Platform/Infrastructure/Legacy/LegacyOperatorLog.php',
        'cli/convert_tables.php',
        'src/Platform/Application/Command/ConvertTables.php',
        'src/Platform/Application/Command/MaintenanceRealm.php',
        'src/Platform/Application/Command/MaintenanceScope.php',
        'src/Platform/Application/Command/MaintenanceTarget.php',
        'src/Platform/Application/Command/SchemaChangeAudit.php',
        'src/Platform/Application/Command/TableConversionStep.php',
        'src/Platform/Application/Port/TableCatalog.php',
        'src/Platform/Application/Port/TableConversion.php',
        'src/Platform/Application/ReadModel/ConversionOutcome.php',
        'src/Platform/Application/ReadModel/ConversionReport.php',
        'src/Platform/Application/ReadModel/TableOutcome.php',
        'src/Platform/Application/ReadModel/TableResult.php',
        'src/Platform/Domain/Schema/ConversionFlag.php',
        'src/Platform/Domain/Schema/ConversionOptions.php',
        'src/Platform/Domain/Schema/ConversionProblem.php',
        'src/Platform/Domain/Schema/InvalidConversionOptions.php',
        'src/Platform/Domain/Schema/TableChange.php',
        'src/Platform/Domain/Schema/TableCharset.php',
        'src/Platform/Domain/Schema/TableSkip.php',
        'src/Platform/Domain/Schema/TableStatus.php',
        'src/Platform/Infrastructure/Legacy/InstallerTableConversion.php',
        'src/Platform/Infrastructure/Legacy/InstallerTableResult.php',
        'src/Platform/Infrastructure/Persistence/DbalTableConversion.php',
        'src/Platform/Infrastructure/Persistence/MaintenanceConnections.php',
        'src/Platform/Infrastructure/Symfony/Console/ConvertTablesCommand.php',
        'src/Platform/Infrastructure/Symfony/Console/ConvertTablesInput.php',
        'src/Platform/Infrastructure/Symfony/Console/ConvertTablesLegacyArguments.php',
        'cli/fix_mediumint.php',
        'src/Platform/Application/Command/WidenIdColumns.php',
        'src/Platform/Application/Port/ColumnCatalog.php',
        'src/Platform/Application/Port/ColumnWidening.php',
        'src/Platform/Application/ReadModel/WideningEvent.php',
        'src/Platform/Application/ReadModel/WideningReport.php',
        'src/Platform/Domain/Schema/ColumnChange.php',
        'src/Platform/Domain/Schema/ColumnDefinition.php',
        'src/Platform/Domain/Schema/IdColumns.php',
        'src/Platform/Domain/Schema/IdColumnPlan.php',
        'src/Platform/Infrastructure/Persistence/DbalColumnWidening.php',
        'src/Platform/Infrastructure/Symfony/Console/WidenIdColumnsCommand.php',
        'src/Platform/Infrastructure/Symfony/Console/WidenIdColumnsInput.php',
        'src/Platform/Infrastructure/Symfony/Console/WidenIdColumnsLegacyArguments.php'];
    if ($handler === 'database') {
        $requiredPaths[] = 'src/IdentityAccess/Infrastructure/Legacy/ReadOnlyDatabaseSessionHandler.php';
    }
    $requiredPaths = array_merge($requiredPaths, $legacyCallerPaths);
    foreach ($requiredPaths as $required) {
        if (!($observed[$required] ?? false)) {
            throw new RuntimeException('Missing measured execution: ' . $required);
        }
    }
    if ($handler !== 'none' && !$wrapperObserved) {
        throw new RuntimeException('Missing physical buffered-cache caller execution: lib/utility.php');
    }
}
foreach (array_keys($mapped) as $path) {
    $coverage->filter()->includeFile($path);
}
$coverage->append(RawCodeCoverageData::fromXdebugWithoutPathCoverage($mapped), 'Symfony HTTP and worker integration');
$temp = tempnam(dirname($argv[5]), 'symfony-clover-');
try {
    (new Clover())->process($coverage, $temp);
    if (!rename($temp, $argv[5])) {
        throw new RuntimeException('Cannot publish Symfony coverage');
    }
} finally {
    if (is_file($temp)) {
        unlink($temp);
    }
}
echo 'Combined Symfony unit, HTTP and worker coverage written', PHP_EOL;
