<?php

/*
 * SPDX-FileCopyrightText: 2026 The Kadupul project and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData;
use SebastianBergmann\CodeCoverage\Report\Clover;

$root = dirname(__DIR__, 2);
require $root . '/include/vendor/autoload.php';
if ($argc !== 6) {
    throw new RuntimeException('Usage: merge_coverage.php UNIT.php FILE_SESSIONS DATABASE_SESSIONS OFFLINE_TOOLS OUTPUT.xml');
}
// This serialized artifact is generated by PHPUnit in this same job.
$coverage = require $argv[1];
if (!$coverage instanceof CodeCoverage) {
    throw new RuntimeException('Invalid Symfony unit coverage');
}
$mapped = [];
foreach ([2 => 'files', 3 => 'database', 4 => 'none'] as $argument => $handler) {
    $manifest = json_decode(file_get_contents($argv[$argument] . '/observations.json'), true, 512, JSON_THROW_ON_ERROR);
    $suite = $handler === 'none' ? 'offline-tools' : 'symfony-http';
    if (($manifest['suite'] ?? '') !== $suite || ($manifest['session_handler'] ?? '') !== $handler) {
        throw new RuntimeException('Wrong integration suite or session handler');
    }
    $scripts = $handler === 'none' ? ['offline_coverage.py'] : ['session_bridge.py', 'inventory_scenarios.py', 'details_scenarios.py', 'site_scenarios.py', 'site_catalog_scenarios.py', 'device_edit_scenarios.py', 'coverage_support.py'];
    foreach ($scripts as $script) {
        $path = 'tests/Symfony/' . $script;
        if (($manifest['source_sha256'][$path] ?? '') !== hash_file('sha256', $root . '/' . $path)) {
            throw new RuntimeException('Integration test source differs from checkout');
        }
    }
    $checks = $handler === 'none' ? ['disconnected archive verified', 'dependency repair verified', 'invalid manifest and symlink rejected'] : [
        'query parameters cannot select an authenticated session', 'deleted account cannot use persisted session',
        'Symfony command disables device polling', 'CSV quotes multiline Unicode text and neutralizes formulas',
        'site counts exclude hidden and deleted devices'];
    foreach ($checks as $check) {
        if (!in_array($check, $manifest['checks'] ?? [], true)) {
            throw new RuntimeException('Incomplete Symfony integration checks');
        }
    }
    $reports = glob($argv[$argument] . '/raw/coverage-*.json');
    if (!$reports) {
        throw new RuntimeException('Missing integration coverage reports');
    }
    $observed = [];
    foreach ($reports as $report) {
        $data = json_decode(file_get_contents($report), true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($data['files'] ?? null) || !is_string($data['php'] ?? null)) {
            throw new RuntimeException('Malformed integration coverage report');
        }
        foreach ($data['files'] as $path => $file) {
            if (!str_starts_with($path, '/var/www/html/')) {
                throw new RuntimeException('Unexpected integration source path');
            }
            $relative = substr($path, strlen('/var/www/html/'));
            // Legacy application coverage has its own report. Never import
            // generated configuration/cache, dependencies or installed plugins.
            if (!str_starts_with($relative, 'src/') && !in_array($relative, ['bin/legacy-device-edit.php', 'app.php', 'public/index.php', 'config/bootstrap.php', 'tools/verify-offline.php', 'tools/dependencies/install-legacy.php'], true)) {
                continue;
            }
            $local = $root . '/' . $relative;
            if (realpath($local) !== $local || !is_file($local)) {
                throw new RuntimeException('Invalid integration source path');
            }
            if (!is_array($file) || ($file['sha256'] ?? null) !== hash_file('sha256', $local)) {
                throw new RuntimeException('Covered source differs from checkout');
            }
            if (!is_array($file['lines'] ?? null)) {
                throw new RuntimeException('Invalid line coverage inventory');
            }
            $lineCount = substr_count(file_get_contents($local), "\n") + 1;
            foreach ($file['lines'] as $line => $hit) {
                if (!is_int($line) || $line < 1 || $line > $lineCount || !in_array($hit, [-1, 1], true)) {
                    throw new RuntimeException('Invalid PCOV line observation');
                }
                $mapped[$local][$line] = max($mapped[$local][$line] ?? -1, $hit);
                $observed[$relative] = ($observed[$relative] ?? false) || $hit === 1;
            }
        }
    }
    $requiredPaths = $handler === 'none' ? ['tools/verify-offline.php', 'tools/dependencies/install-legacy.php'] : [
        'bin/legacy-device-edit.php', 'src/IdentityAccess/Infrastructure/Legacy/SharedSession.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceEditController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteListController.php'];
    foreach ($requiredPaths as $required) {
        if (!($observed[$required] ?? false)) {
            throw new RuntimeException('Missing measured execution: ' . $required);
        }
    }
}
foreach (array_keys($mapped) as $path) {
    $coverage->filter()->includeFile($path);
}
$coverage->append(RawCodeCoverageData::fromXdebugWithoutPathCoverage($mapped), 'Symfony HTTP and worker integration');
$temp = tempnam(dirname($argv[5]), 'symfony-clover-');
try {
    (new Clover())->process($coverage, $temp);
    if (!rename($temp, $argv[5])) {
        throw new RuntimeException('Cannot publish Symfony coverage');
    }
} finally {
    if (is_file($temp)) {
        unlink($temp);
    }
}
echo 'Combined Symfony unit, HTTP and worker coverage written', PHP_EOL;
