<?php

/*
 * SPDX-FileCopyrightText: 2026 The Kadupul project and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData;
use SebastianBergmann\CodeCoverage\Report\Clover;

$root = dirname(__DIR__, 2);
require $root . '/include/vendor/autoload.php';
if ($argc !== 6) {
    throw new RuntimeException('Usage: merge_coverage.php UNIT.php FILE_SESSIONS DATABASE_SESSIONS OFFLINE_TOOLS OUTPUT.xml');
}
// This serialized artifact is generated by PHPUnit in this same job.
$coverage = require $argv[1];
if (!$coverage instanceof CodeCoverage) {
    throw new RuntimeException('Invalid Symfony unit coverage');
}
$mapped = [];
foreach ([2 => 'files', 3 => 'database', 4 => 'none'] as $argument => $handler) {
    $manifest = json_decode(file_get_contents($argv[$argument] . '/observations.json'), true, 512, JSON_THROW_ON_ERROR);
    $suite = $handler === 'none' ? 'offline-tools' : 'symfony-http';
    if (($manifest['suite'] ?? '') !== $suite || ($manifest['session_handler'] ?? '') !== $handler) {
        throw new RuntimeException('Wrong integration suite or session handler');
    }
    $scripts = $handler === 'none' ? ['offline_coverage.py'] : ['session_bridge.py', 'inventory_scenarios.py', 'details_scenarios.py', 'site_scenarios.py', 'site_catalog_scenarios.py', 'site_edit_scenarios.py', 'site_create_scenarios.py', 'device_create_scenarios.py', 'device_creation_review_scenarios.py', 'site_creation_probe.php', 'site_lifecycle_scenarios.py', 'site_collector_scenarios.py', 'site_lifecycle_probe.php', 'site_assignment_probe.php', 'site_disable_probe.php', 'database_failure_probe.php', 'site_authorization_probe.php', 'device_edit_scenarios.py', 'device_template_scenarios.py', 'device_collector_scenarios.py', 'device_state_scenarios.py', 'device_removal_scenarios.py', 'device_template_authorization_probe.php', 'coverage_support.py'];
    $sourcePaths = array_map(static fn(string $script): string => 'tests/Symfony/' . $script, $scripts);
    if ($handler !== 'none') {
        $sourcePaths[] = 'tests/Fixtures/plugins/compatibility_test/setup.php';
    }
    foreach ($sourcePaths as $path) {
        if (($manifest['source_sha256'][$path] ?? '') !== hash_file('sha256', $root . '/' . $path)) {
            throw new RuntimeException('Integration test source differs from checkout');
        }
    }
    $checks = $handler === 'none' ? ['disconnected archive verified', 'dependency repair verified', 'invalid manifest and symlink rejected'] : [
        'query parameters cannot select an authenticated session', 'deleted account cannot use persisted session',
        'Symfony command disables device polling', 'CSV quotes multiline Unicode text and neutralizes formulas',
        'site counts exclude hidden and deleted devices', 'site persistence rechecks actor and revision and rolls back rejected saves',
        'site write serializes account, policy, direct and group grant revocations',
        'site rollback cannot restore a revoked session after account re-enabling',
        'Symfony site translations honor the legacy session and ignore locale query overrides',
        'disabled translation overrides a French shared session',
        'French device editor translates labels without changing polling values',
        'device CSV bytes are independent of locale',
        'device polling settings save through Symfony',
        'device template assignment saves through Symfony',
        'collector reassignment replicates primary device to remote',
        'collector replication failure cannot report success',
        'bulk state confirmation disables selected devices',
        'bulk state confirmation enables selected devices',
        'bulk state SQL failure rolls back the whole primary batch',
        'bulk state remote failure cannot report success',
        'device removal retains graphs and disabled data sources',
        'device removal purges graphs and all owned data sources',
        'device removal failure rolls back whole primary batch',
        'device removal rejects shared data-source purge',
        'remote removal failure cannot report success',
        'collector association failure cannot report successful template assignment',
        'SNMP credentials replace through Symfony without disclosure',
        'stored credential rotation survives unrelated edits',
        'all polling fields persist through the legacy adapter',
        'device site assignment saves through Symfony',
        'site reassignment invalidates device and site caches',
        'site creation persists name',
        'site creation updates both legacy cache markers',
        'rejected creations leave all sites unchanged',
        'full site address timezone map and alternate name persist',
        'bulk site deletion succeeds atomically',
        'site locks precede device locks and rejected assignments preserve polling state',
        'transactional SQL failures cannot retry without locks or report a saved ID',
        'bulk duplication succeeds through Symfony',
        'site lifecycle adapter rejects revoked stale and partial writes',
        'legacy site POST is never replayed',
        'online collector site edit writes only to the primary',
        'unreachable primary cannot fall back to local site writes',
        'worker independently rechecks revoked actor permissions',
        'legacy template graph associations are preserved',
        'device creation updates both cache markers',
        'explicit credentials are not replaced by installation defaults',
        'device creation serializes direct authorization revocations',
        'device creation serializes group authorization revocations',
        'remote collector preserves four-byte Unicode notes',
        'SHA384 is preserved without mapping to an invalid protocol'];
    foreach ($checks as $check) {
        if (!in_array($check, $manifest['checks'] ?? [], true)) {
            throw new RuntimeException('Incomplete Symfony integration checks');
        }
    }
    $reports = glob($argv[$argument] . '/raw/coverage-*.json');
    if (!$reports) {
        throw new RuntimeException('Missing integration coverage reports');
    }
    $observed = [];
    foreach ($reports as $report) {
        $data = json_decode(file_get_contents($report), true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($data['files'] ?? null) || !is_string($data['php'] ?? null)) {
            throw new RuntimeException('Malformed integration coverage report');
        }
        foreach ($data['files'] as $path => $file) {
            if (!str_starts_with($path, '/var/www/html/')) {
                throw new RuntimeException('Unexpected integration source path');
            }
            $relative = substr($path, strlen('/var/www/html/'));
            // Legacy application coverage has its own report. Never import
            // generated configuration/cache, dependencies or installed plugins.
            if (!str_starts_with($relative, 'src/') && !in_array($relative, ['bin/legacy-device-edit.php', 'bin/legacy-device-create.php', 'bin/legacy-device-template.php', 'bin/legacy-device-collector.php', 'bin/legacy-device-state.php', 'bin/legacy-device-remove.php', 'app.php', 'sites.php', 'lib/database.php', 'public/index.php', 'config/bootstrap.php', 'tools/verify-offline.php', 'tools/dependencies/install-legacy.php'], true)) {
                continue;
            }
            $local = $root . '/' . $relative;
            if (realpath($local) !== $local || !is_file($local)) {
                throw new RuntimeException('Invalid integration source path');
            }
            if (!is_array($file) || ($file['sha256'] ?? null) !== hash_file('sha256', $local)) {
                throw new RuntimeException('Covered source differs from checkout');
            }
            if (!is_array($file['lines'] ?? null)) {
                throw new RuntimeException('Invalid line coverage inventory');
            }
            $lineCount = substr_count(file_get_contents($local), "\n") + 1;
            foreach ($file['lines'] as $line => $hit) {
                if (!is_int($line) || $line < 1 || $line > $lineCount || !in_array($hit, [-1, 1], true)) {
                    throw new RuntimeException('Invalid PCOV line observation');
                }
                $mapped[$local][$line] = max($mapped[$local][$line] ?? -1, $hit);
                $observed[$relative] = ($observed[$relative] ?? false) || $hit === 1;
            }
        }
    }
    $requiredPaths = $handler === 'none' ? ['tools/verify-offline.php', 'tools/dependencies/install-legacy.php'] : [
        'bin/legacy-device-edit.php', 'src/IdentityAccess/Infrastructure/Legacy/SharedSession.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceEditController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteListController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteEditController.php', 'src/Inventory/Infrastructure/Legacy/LegacySiteEditor.php',
        'src/IdentityAccess/Infrastructure/Legacy/LegacyLocalePreference.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteCreateController.php',
        'src/Inventory/Domain/DevicePolling.php',
        'src/Inventory/Domain/DeviceTemplateAssignment.php',
        'src/Inventory/Domain/DeviceCollectorAssignment.php',
        'src/Inventory/Application/Command/AssignDeviceTemplate.php',
        'src/Inventory/Application/Command/AssignDeviceCollector.php',
        'src/Inventory/Application/Query/PrepareDeviceTemplateAssignment.php',
        'src/Inventory/Application/Query/PrepareDeviceCollectorAssignment.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceTemplateAssignments.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceCollectorAssignments.php',
        'src/Inventory/Infrastructure/Legacy/DeviceWriteAuthorization.php',
        'src/Inventory/Infrastructure/Legacy/DeviceCollectorReplication.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceTemplateType.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceCollectorType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceTemplateController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceCollectorController.php',
        'bin/legacy-device-template.php',
        'bin/legacy-device-collector.php',
        'bin/legacy-device-state.php',
        'bin/legacy-device-remove.php',
        'src/Inventory/Domain/DeviceRemoval.php',
        'src/Inventory/Application/Command/RemoveDevices.php',
        'src/Inventory/Application/Query/PrepareDeviceRemoval.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceRemovals.php',
        'src/Inventory/Infrastructure/Legacy/DeviceRemovalSnapshot.php',
        'src/Inventory/Infrastructure/Legacy/DeviceRemovalDependencies.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceRemovalType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceRemovalController.php',
        'src/Inventory/Domain/DeviceState.php',
        'src/Inventory/Domain/DeviceSelection.php',
        'src/Inventory/Application/Command/SetDevicesEnabled.php',
        'src/Inventory/Application/Query/PrepareDeviceStateChange.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceStates.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceStateType.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceStateController.php',
        'src/Inventory/Domain/DeviceSnmpConfiguration.php',
        'src/Inventory/Domain/DeviceSnmpChange.php',
        'src/Inventory/Infrastructure/Symfony/Form/DeviceSnmpType.php',
        'src/Inventory/Infrastructure/Symfony/Form/DevicePollingType.php',
        'src/Inventory/Application/Query/ListAssignableSites.php',
        'src/Inventory/Infrastructure/Legacy/LegacySiteAssignmentCatalog.php',
        'src/Inventory/Application/Command/CreateSite.php',
        'src/Inventory/Domain/NewSite.php',
        'src/Inventory/Infrastructure/Legacy/LegacySiteCreator.php',
        'src/Platform/Infrastructure/Legacy/CollectorSiteDatabase.php',
        'sites.php',
        'lib/database.php',
        'src/Inventory/Infrastructure/Symfony/Controller/LegacySitesController.php',
        'src/Inventory/Infrastructure/Symfony/Controller/SiteActionController.php',
        'src/Inventory/Infrastructure/Legacy/LegacySiteLifecycle.php',
        'src/Inventory/Application/Command/DeleteSites.php',
        'src/Inventory/Application/Command/DuplicateSites.php',
        'src/Inventory/Application/Query/PrepareSiteAction.php',
        'src/Inventory/Domain/SiteSelection.php',
        'bin/legacy-device-create.php',
        'src/Inventory/Infrastructure/Symfony/Controller/DeviceCreateController.php',
        'src/Inventory/Application/Command/CreateDevice.php',
        'src/Inventory/Application/Query/PrepareDeviceCreation.php',
        'src/Inventory/Domain/NewDevice.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceCreationCatalog.php',
        'src/Inventory/Infrastructure/Legacy/LegacyDeviceCreator.php',
        'src/Platform/Infrastructure/Symfony/InventoryLocaleSubscriber.php'];
    foreach ($requiredPaths as $required) {
        if (!($observed[$required] ?? false)) {
            throw new RuntimeException('Missing measured execution: ' . $required);
        }
    }
}
foreach (array_keys($mapped) as $path) {
    $coverage->filter()->includeFile($path);
}
$coverage->append(RawCodeCoverageData::fromXdebugWithoutPathCoverage($mapped), 'Symfony HTTP and worker integration');
$temp = tempnam(dirname($argv[5]), 'symfony-clover-');
try {
    (new Clover())->process($coverage, $temp);
    if (!rename($temp, $argv[5])) {
        throw new RuntimeException('Cannot publish Symfony coverage');
    }
} finally {
    if (is_file($temp)) {
        unlink($temp);
    }
}
echo 'Combined Symfony unit, HTTP and worker coverage written', PHP_EOL;
