<?php

test('installer replaces only the shipped graph watermark', function (string $stored, string $expected) {
	$installer = var_export(dirname(__DIR__, 2) . '/install/functions.php', true);
	$initial = var_export($stored, true);
	$script = '<?php ' . <<<'CHILD'
$db = new PDO('sqlite::memory:');
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$db->exec('CREATE TABLE settings (name TEXT PRIMARY KEY, value TEXT)');
function db_execute_prepared($sql, $parameters) {
	global $db;
	return $db->prepare($sql)->execute($parameters);
}
$settings = [];
$_SESSION = [];
CHILD;
	$script .= "\nrequire $installer;\n";
	$script .= "db_execute_prepared('INSERT INTO settings VALUES (?, ?)', ['graph_watermark', $initial]);\n";
	$script .= <<<'CHILD'
db_execute_prepared('INSERT INTO settings VALUES (?, ?)', ['other_setting', 'unchanged']);
prime_default_settings();
prime_default_settings();
echo json_encode($db->query('SELECT name, value FROM settings ORDER BY name')->fetchAll(PDO::FETCH_KEY_PAIR));
CHILD;

	$process = proc_open([PHP_BINARY], [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
	expect(is_resource($process))->toBeTrue();
	fwrite($pipes[0], $script);
	fclose($pipes[0]);
	$output = stream_get_contents($pipes[1]);
	$error = stream_get_contents($pipes[2]);
	fclose($pipes[1]);
	fclose($pipes[2]);
	expect(proc_close($process), $error)->toBe(0);
	expect(json_decode($output, true, 512, JSON_THROW_ON_ERROR))->toBe([
		'graph_watermark' => $expected,
		'other_setting' => 'unchanged',
	]);
})->with([
	'shipped default' => ['Generated by Cacti®', 'Generated by Kadupul'],
	'custom watermark' => ['Operations graphs © 2026', 'Operations graphs © 2026'],
	'custom case' => ['generated by cacti®', 'generated by cacti®'],
	'custom spacing' => ['Generated by Cacti® ', 'Generated by Cacti® '],
	'empty watermark' => ['', ''],
	'current default' => ['Generated by Kadupul', 'Generated by Kadupul'],
]);
